---

- name: Start container
  docker_container:
    image: XXX
    name: cortico-data
    command: '{{ command }}'
    state: started
    network_mode: host
    pull: true
    restart: true
    volumes:
      - /etc/spark:/opt/spark-2.2.0/conf
      - /mnt:/mnt
