
version: '3'

services:

  dev:
    build: .
    image: dclure/twitter-ext
    env_file:
      - docker/aws.env
    volumes:
      - ./code:/code
      - ./data:/code/data
    ports:
      - '8888:8888'
