---

- name: Get master facts
  register: master
  ec2_remote_facts:
    filters:
      instance-state-name: running
      'tag:mit': spark-master

- name: Set the master host
  set_fact:
    spark_master_host:
      '{{ master.instances[0].private_dns_name }}'

- name: Set the worker count
  set_fact:
    spark_worker_count:
      '{{ groups["tag_mit_spark-worker"] | length }}'

- name: Set the CPU count on each slave
  set_fact:
    spark_slave_vcpus:
      '{{ hostvars[groups["tag_mit_spark-worker"][0]]
      ["ansible_processor_vcpus"] }}'
