---

spark_master_host: localhost
spark_master_port: 7077
spark_master_url: spark://{{ spark_master_host }}:{{ spark_master_port }}

# On EC2, use public DNS.
spark_public_dns: >
  `wget -q -O - http://169.254.169.254/latest/meta-data/public-hostname ||
   wget -q -O - http://169.254.169.254/latest/meta-data/local-ipv4`

spark_tasks_per_core: 3

spark_default_parallelism: '{{
  spark_worker_count|int *
  spark_worker_vcpus|int *
  spark_tasks_per_core
}}'

spark_packages:
  - org.apache.hadoop:hadoop-aws:2.7.3

spark_max_files: 100000
spark_s3_connection_timeout: 3600000
spark_s3_max_retries: 50
spark_task_max_failures: 20

# TODO: Derive from cluster role?

spark_executor_memory: 1g
spark_driver_memory: 1g

spark_hadoop_tmp_dir: /mnt/hadoop
spark_hadoop_conf_dir: /etc/hadoop
spark_local_dir: /mnt/spark
